In [1]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [5]:
b= np.array([[5,7,8],[7,3,4]])

In [11]:
m= np.array[[[3,8,4,],[9,3,5],[11,15,17]]],[19,31,8],[[[41],[81],[71]],[[31][11][51]],[[61],[91],[131]]

SyntaxError: incomplete input (1114068374.py, line 1)

In [13]:
k = np.array([[4,8,7],[3,1,5],[6,9,13]])
k

array([[ 4,  8,  7],
       [ 3,  1,  5],
       [ 6,  9, 13]])

In [15]:
k[:2,]

array([[4, 8, 7],
       [3, 1, 5]])

In [16]:
k[:2,1]

array([8, 1])

In [17]:
k[:3,1]

array([8, 1, 9])

In [18]:
k[:1,2]

array([7])