In [50]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [51]:
pip install scikit-image

Note: you may need to restart the kernel to use updated packages.


In [52]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [53]:
np.array ([1,2,3,4,5,6,7,8,9,10])


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
!python -m pip install numpy

In [55]:
import numpy as np

In [56]:
np.array ([1,2,3,4,5,6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
np.arange(1,11,1.5)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [58]:
list (range(1,10,11))

[1]

In [59]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [60]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
np.random.randint(1,100,[3,5])

array([[42, 81, 98,  4, 46],
       [46, 66, 93, 60, 81],
       [ 7, 54, 50, 18, 22]])

In [63]:
np.random.seed(5)
np.random.randint(1,100,[3,5])

array([[79, 62, 17, 74,  9],
       [63, 28, 31, 81,  8],
       [77, 16, 54, 81, 28]])

In [64]:
np.random.seed(5999)
np.random.randint(1,100,[3,5])

array([[18, 97, 52,  5, 89],
       [19, 33, 50, 63, 37],
       [93, 40, 52, 46, 93]])

In [65]:
np.random.randn(3,4)

array([[ 0.61047877,  1.49511068, -0.77610236, -0.51130803],
       [ 0.61338151, -0.78226392,  0.9111316 , -0.65388296],
       [-0.99047799,  0.36320302, -0.62107921,  1.27478692]])

In [66]:
import random

In [67]:
np.loadtxt('data.txt',delimiter=',')

C:\Users\t1340\AppData\Local\Temp\ipykernel_13468\3740574567.py:1: UserWarning: loadtxt: input contained no data: "data.txt"
  np.loadtxt('data.txt',delimiter=',')


array([], dtype=float64)

In [68]:
np.loadtxt('data1.txt',dlimiter=',')

TypeError: loadtxt() got an unexpected keyword argument 'dlimiter'

In [ ]:
np

<module 'numpy' from 'c:\\Users\\t1340\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [ ]:
k.mean(axis=1)

NameError: name 'k' is not defined

In [73]:
a=np.array([1,10])

In [74]:
a

array([ 1, 10])

In [75]:
a=np.random.randint(10,100,[3,6])

In [76]:
a

array([[51, 90, 13, 55, 55, 75],
       [69, 90, 16, 63, 59, 27],
       [31, 41, 86, 21, 30, 17]])

In [77]:
a.mean(axis=1)

array([56.5       , 54.        , 37.66666667])